# Generated by Django 3.1.2 on 2020-10-05 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desarrollo',
            name='leads',
        ),
        migrations.AddField(
            model_name='leads',
            name='desarrollo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desarrollos.desarrollo'),
        ),
    ]
